apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: snappass
    name: snappass
    tier: backend
  name: snappass
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: snappass
  type: ClusterIP
status:
  loadBalancer: {}
