apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: snappass
    name: snappass-redis
    tier: backend
  name: snappass-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: snappass
  type: ClusterIP
status:
  loadBalancer: {}
